### ISSUE TITLE
Frequency of dependency update?

### ISSUE THREAD

**Issue by jmh530** [dlang-tour/core-exec#46]
How frequently does run.dlang.org check for updates on dependencies for packages supported?

There was a new release on mir-lapack within the past two days, but I didn't notice the new code working yet on run.dlang.org.

Thanks.

**Comment by wilzbach** [comment]
The auto-update is currently broken, but otherwise it would be once a day.

**Comment by jmh530** [comment]
@wilzbach Now mir-algorithm isn't working at all on run.dlang.org https://run.dlang.io/is/YP1MzW

**Comment by PetarKirov** [comment]
@jmh530 You can use the following script to check which dub packages are available on dlang-tour:

```D
import std;

void main()
{
    "%-(%s\n%)"
        .writefln(
            "/sandbox/.dub/packages".dirEntries(SpanMode.shallow)
            .filter!(d => d.isDir)
            .map!(d => d.baseName)
        );
}
```

https://run.dlang.io/gist/run-dlang/2d14f8453f4e539009788f5cd9d87060?compiler=dmd-beta

As you can see, the following mir packages are available:
```
mir-3.2.0
mir-algorithm-3.4.2
mir-blas-1.1.4
mir-core-0.3.4
mir-lapack-1.0.4
mir-linux-kernel-1.0.1
mir-random-2.2.4
```

And the following should work:
```D
/+dub.sdl:
dependency "mir-algorithm" version="~>3.4"
+/
void main() {
    
}
```

**Comment by PetarKirov** [comment]
An even simpler and more idiomatic way to list the available dub packages is:

```D
void main()
{
    import std.process;
    "dub list".spawnShell.wait;
}
```

https://run.dlang.io/gist/run-dlang/19388206bf0b4370886a6835ffae5675

**Comment by jmh530** [comment]
@ZombineDev These are both great suggestions. However, if you go to run.dlang.org, then the mir-algorithm that is in the dropdown is 3.3.11, not 3.4.0. So your advice is good for someone who knows how to do this, but many with less patience would just see it as broken and move on. The version in the dropdown should match the version that is actually imported.

**Comment by wilzbach** [comment]
Understood, for the dropdown menu there's an update task in the API, but I think currently we only update that when the tour gets updated, which used to be every day, but the Travis build is broken these days :/

Anyhow, here are the respective lines in the app:

https://github.com/dlang-tour/core/blob/9014e140e5006a6e58400924c8a4729a5cd43db7/source/app.d#L205-L206

**Comment by jmh530** [comment]
@wilzbach So my sense is that all these issues will go away when the Travis build is fixed?

**Comment by PetarKirov** [comment]
@jmh530 Yes, and I'm working on that.
