### ISSUE TITLE
Adjust entrypoint.sh for newer druntime versions

### ISSUE THREAD

**Issue by PetarKirov** [dlang-tour/core-exec#50]
See: https://github.com/dlang/druntime/pull/2877

**Comment by schveiguy** [comment]
I'm trying to find where -unittest is passed to dmd. Where is that?

**Comment by PetarKirov** [comment]
Actually, it seems like there's no problem here after all. See: https://github.com/dlang/dlang.org/blob/9222574851f9e85728cbce69e8dac27b162a1258/js/run.js#L104

**Comment by wilzbach** [comment]
> Actually, it seems like there's no problem here after all.

Let's still add support for passing runtime args:

dlang-tour/core#743
dlang-tour/core-exec#51
https://github.com/dlang/dlang.org/pull/2739
