### ISSUE TITLE
Dub Dependencies Haven't Updated Since April 21

### ISSUE THREAD

**Issue by jmh530** [dlang-tour/core-exec#69]
`run.dlang.org` currently lists using `mir-algorithm` 3.12.31 when the most recent version (as of this writing) is 3.14.10

**Comment by jmh530** [comment]
It still has roughly the same amount of lag. The mir-algorithm listed on the site is 3.19.1, which was released February 7 2023.

**Comment by PetarKirov** [comment]
In general, there is a CI cron job that pulls the latest versions of the packages when building the docker images. Unfortunately, the CI started failing a while ago and I haven't had the chance to fix it. See e.g.:

https://github.com/dlang-tour/core-exec/actions/runs/5827408991/job/15803364188

**Comment by jmh530** [comment]
Unfortunately, it isn't entirely obvious from that why it is failing. I did notice that the `run-test-shell` appears to start failing a little bit after commit d8b29ef0b (suggesting that is not a problem but something starts happening after that). When you push your March commits it is green initially and then reverts back to failing.

https://github.com/dlang-tour/core-exec/actions/workflows/run-test-sh.yml?page=8
